version: '3.4'

services:
  desafiogreatbackend:
    image: desafiogreatbackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "acp13126"
        ACCEPT_EULA: "Y"